### ISSUE TITLE
Fix linking of domain name billsworld.co.nz to bills-world.herokuapp.com

### ISSUE THREAD

**Issue by alex-blair** [matai-2016/Bills-World#120]

**Comment by james-mead** [comment]
This issue is in related to pointing the record billsworld.co.nz at an A record which does not have a static IP. Unfortunately a lot of providers in NZ don't support pointing the root domain at the CNAME, e.g. billsworld.co.nz > billsworld.co.nz.herokudns.com. 

I will drop an email to 1stdomains.co.nz to see if they have any bright ideas. 
I suspect we will either need to purchase a static IP address @ heroku or; use another provider for managing the domain records.

**Comment by james-mead** [comment]
Resolved. Pointed domain billsworld.co.nz to CloudFlare's name servers. Pointed root domain billsworld.co.nz to billsworld.co.nz.herokudns.com using a CNAME.
